######################################################################
#
# File name : cfg_tb_multiplier_compile.do
# Created on: Sat Mar 19 19:54:46 +0000 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vcom  -93 -work xil_defaultlib  \
"../../../../project_2.srcs/sources_1/new/multiplier.vhd" \
"../../../../project_2.srcs/sim_1/new/tb_multiplier.vhd" \


quit -force

